# Generated by Django 3.1.2 on 2020-10-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='buying_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
