# Generated by Django 3.1.2 on 2020-10-11 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_stocked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocked',
            old_name='Drug_name',
            new_name='drug_name',
        ),
    ]
