# Generated by Django 3.1.2 on 2020-10-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_auto_20201011_1520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocked',
            options={'verbose_name': 'Stock Addition', 'verbose_name_plural': 'Stock Additions'},
        ),
        migrations.AddField(
            model_name='stocked',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
