# Generated by Django 3.1.2 on 2020-10-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0006_sale_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocked',
            name='supplier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
