# Generated by Django 3.1.2 on 2020-10-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0009_auto_20201019_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='customer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
