# Generated by Django 3.1.2 on 2020-10-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0010_auto_20201020_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='customer',
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
