# Generated by Django 3.1.2 on 2020-10-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0011_auto_20201020_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
