# Generated by Django 3.1.2 on 2020-10-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0012_auto_20201020_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='minimum_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
